# COGNOME NOME

# Esercizio 1
Creare un notebook jupyter che a partire dal testo contenuto nel file ___"J_Verne_girodelmondoin80giorni.txt"___:

1. crei un dizionario delle frequenze per ciascun carattere (**line feed escluso**); 
2. crei il dizionario delle adiacenze per ciascun carattere (**line feed escluso**);
3. **[FACOLTATIVO]** crei un indice dei capitoli. Ogni capitolo inizia riportando il numero romano del capitolo e il suo titolo in questo modo:

>CAPITOLO XXIX.
>
>Nel quale si narrano cose che capitano unicamente sulle ferrovie
>americane.

In [4]:
# Leggere il testo dal file
with open("J_Verne_girodelmondoin80giorni.txt", "r", encoding="utf-8") as file:
    testo = file.read()
# Creare un dizionario delle frequenze per ciascun carattere (escludendo il carattere di ritorno a capo)
diz_freq = {}
for char in testo:
    if char != '\n':
        if char in diz_freq:
            diz_freq[char] += 1
        else:
            diz_freq[char] = 1
# Stampare il dizionario delle frequenze dei caratteri
print("Dizionario delle frequenze dei caratteri:")
print(diz_freq)

Dizionario delle frequenze dei caratteri:
{' ': 59718, 'I': 916, 'L': 498, 'G': 590, 'R': 169, 'O': 231, 'D': 231, 'E': 532, 'M': 422, 'N': 329, 'T': 189, 'A': 632, 'U': 145, 'V': 157, 'F': 1178, 'S': 665, ',': 6381, '—': 896, '=': 2, 'Q': 192, 'u': 10152, 'i': 32215, 'n': 22842, 'd': 11885, 'c': 12687, 'e': 36940, 's': 18049, 'm': 8352, 'o': 29700, 'g': 8240, 'l': 20506, 'a': 37759, '.': 4127, '_': 858, 'p': 8380, 'r': 21059, 't': 19567, 'è': 607, 'v': 7140, 'à': 526, '’': 1877, 'C': 550, '1': 104, '9': 15, '4': 29, 'P': 639, 'q': 1741, 'h': 3337, 'b': 3738, '8': 33, '7': 28, '2': 73, '-': 311, 'w': 116, 'B': 250, 'ì': 431, '[': 16, ']': 16, 'ù': 349, 'f': 3205, 'z': 2363, 'y': 254, 'k': 181, 'ò': 840, '?': 360, ';': 179, '!': 595, 'J': 48, '“': 267, '„': 248, 'é': 4, 'H': 137, ':': 158, 'K': 112, '(': 45, '3': 28, '5': 46, ')': 45, 'È': 52, '0': 107, 'Y': 83, '6': 14, 'x': 291, '/': 2, 'X': 57, 'j': 42, 'î': 1, 'Z': 3, 'ô': 8, 'ê': 2, 'á': 2, 'W': 20, 'º': 2}


In [9]:

# Creare un dizionario delle adiacenze per ciascun carattere (escludendo il carattere di ritorno a capo)
diz_adiacenze = {}
for i, char in enumerate(testo[:-1]):
    if char != '\n' and testo[i + 1] != '\n':
        if char in diz_adiacenze:
            diz_adiacenze[char].append(testo[i+1])
        else:
            diz_adiacenze[char] = [testo[i+1]]

# Stampare il dizionario delle adiacenze
print("\nDizionario delle adiacenze:")
diz_adiacenze


Dizionario delle adiacenze:


{' ': [' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'I',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'G',
  'D',
  'M',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'I',
  'O',
  'G',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  'D',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
  ' ',
 

In [17]:
with open("J_Verne_girodelmondoin80giorni.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()
    for i, line in enumerate(lines):
        if line.startswith("CAPITOLO"):
            print(line, end="") #stampa capitolo I, capitolo II ecc.
            k = i + 2
            while lines[k] != '\n':
                print(lines[k],end="")
                k += 1
            print("")

CAPITOLO PRIMO.
Nel quale Phileas Fogg e Gambalesta si accettano reciprocamente l’uno
come padrone l’altro come servitore.

CAPITOLO II.
Nel quale Gambalesta è convinto d’aver finalmente trovato il suo ideale.

CAPITOLO III.
Nel quale s’impegna una conversazione che potrà costar caro a Phileas
Fogg.

CAPITOLO IV.
Nel quale Phileas Fogg sbalordisce Gambalesta, suo servo.

CAPITOLO V.
Nel quale un nuovo valore comparisce sulla piazza di Londra.

CAPITOLO VI.
Nel quale l’agente Fix mostra un’impazienza più che legittima.

CAPITOLO VII.
Che prova una volta di più l’inutilità dei passaporti in materia di
polizia.

CAPITOLO VIII.
Nel quale Gambalesta parla forse un po’ più del bisogno.

CAPITOLO IX.
Dove il mar Rosso e il mar delle Indie si mostrano propizii ai disegni
di Phileas Fogg.

CAPITOLO X.
Dove Gambalesta è felicissimo di non perdere che le scarpe.

CAPITOLO XI.
Dove Phileas Fogg compra a prezzo favoloso una cavalcatura.

CAPITOLO XII.
Nel quale Phileas Fogg e i suoi compagni si avv

# Esercizio 2
Dato `n`numero intero maggiore o uguale a 2 crea una matrice di numpy che abbia la struttura seguente esemplificata, per il caso `n=7`. 

`[[1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]]`
 

In [26]:
import numpy as np


n = 5 # Puoi cambiare il valore di n

# Creazione della matrice base con zeri
matrice = np.zeros((n, n))

# Assegna 1 e 2 alternativamente usando slicing
matrice[::2, ::2] = 1
matrice[1::2, 1::2] = 1
matrice[::2, 1::2] = 2
matrice[1::2, ::2] = 2

print(matrice)


[[1. 2. 1. 2. 1.]
 [2. 1. 2. 1. 2.]
 [1. 2. 1. 2. 1.]
 [2. 1. 2. 1. 2.]
 [1. 2. 1. 2. 1.]]


# Esercizio 3
Crea un array unidimensionale di numpy lungo 21 elementi i cui valori sono 1,2 e 3 alernatici ciclicamente (`[1,2,3,1,2,3,.....]`).

In [34]:
import numpy as np

lunghezza = 21

array_ciclico = np.zeros(lunghezza, dtype=int)
array_ciclico[0::3] = 1
array_ciclico[1::3] = 2
array_ciclico[2::3] = 3
array_ciclico

#metoto furbo
array_furbo = np.array([1,2,3]*7)
array_furbo

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])